use_frameworks!

platform :ios, '9.0'

target 'HelloWorld_Example' do
  pod 'HelloWorld', :path => '../'

  target 'HelloWorld_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
